version: '2'
services:
    dictionary-app:
        image: dictionary
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dictionary-postgresql:5432/dictionary
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=dictionary-elasticsearch:9300
        ports:
            - 8080:8080
    dictionary-postgresql:
        extends:
            file: postgresql.yml
            service: dictionary-postgresql
    dictionary-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dictionary-elasticsearch
