version: '2'
services:
    dictionary-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/dictionary/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=dictionary
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
